// Command richmessage demonstrates Bot API 10.1's Rich Messages
// (sendRichMessage/sendRichMessageDraft). Most commands build their content
// with golagram's RichBlock/RichText constructors (gg.RichParagraph,
// gg.RichTable, gg.RichPhoto, ...) and gg.RenderRichMessage — see /media for
// the boundary the builder still enforces (decode-only media types with a
// Telegram file reference instead of a URL) and /markdown for the one thing
// it deliberately doesn't cover at all (Markdown output; the builder only
// targets HTML). Reading one back uses gg.RichMessage.PlainText (see
// richmessage_reader.go in the root package) — forward one of this bot's
// own replies back to it to see it in action. Run it with:
//
//	export BOT_TOKEN=your-token-from-botfather
//	go run ./examples/richmessage
package main

import (
	"context"
	"log"
	"os"
	"os/signal"
	"syscall"
	"time"

	gg "github.com/apizbe/golagram"
)

func main() {
	token := os.Getenv("BOT_TOKEN")
	if token == "" {
		log.Fatal("set BOT_TOKEN to a token from @BotFather")
	}

	bot, err := gg.NewTelegramBot(token)
	if err != nil {
		log.Fatal(err)
	}

	r := gg.NewRouter()

	r.Message(gg.FilterCommand("start")).Handle(func(c *gg.Ctx) error {
		_, err := c.Answer("Rich Messages demo. Try:\n" +
			"/headings /table /list /quote /details /media /math /special\n" +
			"/markdown — the same content expressed as Markdown instead of HTML\n" +
			"/draft — streaming a partial rich message before finalizing\n\n" +
			"Forward any of my replies back to me to see the reader walk the block tree.")
		return err
	})

	r.Message(gg.FilterCommand("headings")).Handle(func(c *gg.Ctx) error {
		return sendRichBlocks(c,
			gg.RichHeading(1, gg.RichPlain("Heading 1")),
			gg.RichHeading(2, gg.RichPlain("Heading 2")),
			gg.RichHeading(3, gg.RichPlain("Heading 3")),
			gg.RichParagraph(gg.RichPlain("A plain paragraph between headings.")),
			gg.RichDivider(),
			gg.RichFooter(gg.RichPlain("Generated by the richmessage example")),
		)
	})

	r.Message(gg.FilterCommand("table")).Handle(func(c *gg.Ctx) error {
		onTime := gg.RichCell(gg.RichPlain("on time"))
		onTime.Align = "center"
		gadgetQty := gg.RichCell(gg.RichPlain("1"))
		gadgetQty.Rowspan = 2
		return sendRichBlocks(c, gg.RichTable(true, true, gg.RichPlain("Q2 Orders"),
			[]gg.RichBlockTableCell{gg.RichHeaderCell(gg.RichPlain("Item")), gg.RichHeaderCell(gg.RichPlain("Qty")), gg.RichHeaderCell(gg.RichPlain("Notes"))},
			[]gg.RichBlockTableCell{gg.RichCell(gg.RichPlain("Widget")), gg.RichCell(gg.RichPlain("3")), onTime},
			[]gg.RichBlockTableCell{gg.RichCell(gg.RichPlain("Gadget")), gadgetQty, gg.RichCell(gg.RichPlain("backordered"))},
			[]gg.RichBlockTableCell{gg.RichCell(gg.RichPlain("1")), gg.RichCell(gg.RichPlain("partial ship"))},
		))
	})

	r.Message(gg.FilterCommand("list")).Handle(func(c *gg.Ctx) error {
		return sendRichBlocks(c,
			gg.RichParagraph(gg.RichPlain("Unordered:")),
			gg.RichList(gg.RichItem(gg.RichParagraph(gg.RichPlain("Coffee"))), gg.RichItem(gg.RichParagraph(gg.RichPlain("Tea")))),
			gg.RichParagraph(gg.RichPlain("Ordered:")),
			gg.RichList(gg.RichOrderedItem(gg.RichParagraph(gg.RichPlain("Preheat oven"))), gg.RichOrderedItem(gg.RichParagraph(gg.RichPlain("Bake 20 minutes")))),
			gg.RichParagraph(gg.RichPlain("Checklist:")),
			gg.RichList(
				gg.RichCheckItem(true, gg.RichParagraph(gg.RichPlain("Ship order"))),
				gg.RichCheckItem(false, gg.RichParagraph(gg.RichPlain("Send invoice"))),
			),
		)
	})

	r.Message(gg.FilterCommand("quote")).Handle(func(c *gg.Ctx) error {
		return sendRichBlocks(c,
			gg.RichBlockquote(gg.RichPlain("A Wiser Engineer"), gg.RichParagraph(gg.RichPlain("Move fast and fix things."))),
			gg.RichPullquote(gg.RichPlain("The Team"), gg.RichPlain("Ship small, ship often.")),
		)
	})

	r.Message(gg.FilterCommand("details")).Handle(func(c *gg.Ctx) error {
		return sendRichBlocks(c, gg.RichDetails(false, gg.RichPlain("What's in this release?"),
			gg.RichHeading(3, gg.RichPlain("Changelog")),
			gg.RichParagraph(gg.RichPlain("Rich Messages support, now with tables and collapsible sections.")),
		))
	})

	r.Message(gg.FilterCommand("media")).Handle(func(c *gg.Ctx) error {
		// The builder does refuse the *decode-only* media types: a bare
		// RichBlockPhoto carries a Telegram file reference, not a URL, so
		// there's nothing to render. Demonstrate the boundary, then build
		// the collage for real with RichPhoto, which originates a photo
		// from a URL instead.
		if _, err := gg.RenderRichMessage(&gg.RichBlockPhoto{Type: "photo"}); err != nil {
			log.Printf("expected: %v", err)
		}

		first := gg.RichPhoto("https://picsum.photos/seed/1/400")
		first.Caption = &gg.RichBlockCaption{Text: gg.RichPlain("First shot"), Credit: gg.RichPlain("Photographer A")}

		second := gg.RichPhoto("https://picsum.photos/seed/2/400")
		second.Spoiler = true
		second.Caption = &gg.RichBlockCaption{Text: gg.RichPlainText("Second shot"), Credit: gg.RichPlain("Photographer B")}

		return sendRichBlocks(c, gg.RichCollage(first, second))
	})

	r.Message(gg.FilterCommand("math")).Handle(func(c *gg.Ctx) error {
		return sendRichBlocks(c,
			gg.RichParagraph(gg.RichPlain("Einstein's famous inline formula: "), gg.RichInlineMath("E = mc^2"), gg.RichPlain(".")),
			gg.RichMathBlock(`\int_0^1 x^2 \,dx = \frac{1}{3}`),
		)
	})

	r.Message(gg.FilterCommand("special")).Handle(func(c *gg.Ctx) error {
		// Date/time and footnote references have no builder constructor —
		// direct struct literals, same as building an InlineKeyboardButton
		// one field at a time, work just as well: RenderRichMessage type
		// switches on the same generated types either way.
		taggedNow := &gg.RichTextDateTime{
			Type:           "date_time",
			Text:           gg.RichPlain("right now"),
			UnixTime:       time.Now().Unix(),
			DateTimeFormat: "wDT",
		}
		footnote := &gg.RichTextReference{Type: "reference", Name: "src1", Text: gg.RichPlain("[1]")}
		return sendRichBlocks(c,
			gg.RichParagraph(gg.RichPlain("Meet "), gg.RichUserMention(c.From()), gg.RichPlain(", tagged at "), taggedNow, gg.RichPlain(".")),
			gg.RichParagraph(gg.RichAnchorPoint("notes"), gg.RichPlain("See the "), gg.RichAnchorLink("notes", gg.RichPlain("notes anchor")), gg.RichPlain(" above.")),
			gg.RichParagraph(gg.RichPlain("Footnote example"), footnote, gg.RichPlain(".")),
		)
	})

	r.Message(gg.FilterCommand("markdown")).Handle(func(c *gg.Ctx) error {
		md := "# Markdown heading\n\n" +
			"**bold**, *italic*, ~~strikethrough~~, `code`, ==marked==, ||spoiler||\n\n" +
			"- unordered item\n" +
			"- [x] done task\n" +
			"- [ ] open task\n\n" +
			">A block quotation in Markdown.\n\n" +
			"$x^2 + y^2 = z^2$\n\n" +
			"Inline mention: [our repo](https://github.com/apizbe/golagram)"
		_, err := c.Bot().SendRichMessage(c, &gg.SendRichMessageRequest{
			ChatID:      gg.ChatIDFromInt(c.Chat().ID),
			RichMessage: &gg.InputRichMessage{Markdown: md},
		})
		return err
	})

	r.Message(gg.FilterCommand("draft")).Handle(func(c *gg.Ctx) error {
		chatID := c.Chat().ID
		draftID := time.Now().UnixNano() // must be non-zero and unique per in-flight draft

		// sendRichMessageDraft streams an ephemeral preview (auto-expires
		// after 30s) — RichThinking (<tg-thinking>) is only legal here,
		// never in the final sendRichMessage call.
		steps := [][]gg.RichBlock{
			{gg.RichThinking(gg.RichPlain("Thinking…"))},
			{gg.RichParagraph(gg.RichPlain("Drafting your answer"))},
			{
				gg.RichParagraph(gg.RichPlain("Drafting your answer"), gg.RichBold(gg.RichPlain("…"))),
				gg.RichParagraph(gg.RichPlain("Almost done")),
			},
		}
		for _, step := range steps {
			msg, err := gg.RenderRichMessage(step...)
			if err != nil {
				return err
			}
			if _, err := c.Bot().SendRichMessageDraft(c, &gg.SendRichMessageDraftRequest{
				ChatID:      chatID,
				DraftID:     draftID,
				RichMessage: msg,
			}); err != nil {
				return err
			}
			time.Sleep(700 * time.Millisecond)
		}

		// Finalize: the streamed draft never lands in history on its own —
		// this sendRichMessage call is what actually persists a message.
		return sendRichBlocks(c, gg.RichParagraph(gg.RichPlain("Here's your final, persisted answer.")))
	})

	// Reader: any incoming message carrying a parsed RichMessage (easiest
	// way to trigger one without a rich-text-capable client: forward one
	// of this bot's own replies back to it) gets flattened back to plain
	// text via gg.RichMessage.PlainText — no hand-written walker needed.
	r.Message(func(c *gg.Ctx) bool {
		return c.Message != nil && c.Message.RichMessage != nil
	}).Handle(func(c *gg.Ctx) error {
		_, err := c.Answer("Parsed rich message:\n\n" + c.Message.RichMessage.PlainText())
		return err
	})

	bot.Dispatch(r)

	ctx, stop := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer stop()

	log.Println("richmessage bot running — press Ctrl+C to stop")
	if err := bot.Run(ctx); err != nil {
		log.Fatal(err)
	}
}

// sendRichBlocks renders blocks via gg.RenderRichMessage and sends the
// result — still no Ctx.ReplyRich sugar (business connection/thread ID/
// reply parameters would need setting by hand, same as SendRichMessage
// always has), but the content itself no longer needs a hand-written
// HTML string.
func sendRichBlocks(c *gg.Ctx, blocks ...gg.RichBlock) error {
	msg, err := gg.RenderRichMessage(blocks...)
	if err != nil {
		return err
	}
	_, err = c.Bot().SendRichMessage(c, &gg.SendRichMessageRequest{
		ChatID:      gg.ChatIDFromInt(c.Chat().ID),
		RichMessage: msg,
	})
	return err
}
