// Code generated by internal/gen from Bot API 10.1. DO NOT EDIT.
// Regenerate with: go generate ./...

package golagram

// ChatType values for Chat.Type, scraped from Chat.type's docs description.
const (
	ChatTypePrivate    = "private"
	ChatTypeGroup      = "group"
	ChatTypeSupergroup = "supergroup"
	ChatTypeChannel    = "channel"
)

// MessageEntity.Type values, scraped from MessageEntity.type's docs description.
// Formatting-only entities (Bold, Italic, ...) are included even though
// [FilterHasEntity]'s doc comment steers callers toward the content-bearing
// ones (Mention, Hashtag, URL, ...) instead.
const (
	EntityMention              = "mention"
	EntityHashtag              = "hashtag"
	EntityCashtag              = "cashtag"
	EntityBotCommand           = "bot_command"
	EntityURL                  = "url"
	EntityEmail                = "email"
	EntityPhoneNumber          = "phone_number"
	EntityBold                 = "bold"
	EntityItalic               = "italic"
	EntityUnderline            = "underline"
	EntityStrikethrough        = "strikethrough"
	EntitySpoiler              = "spoiler"
	EntityBlockquote           = "blockquote"
	EntityExpandableBlockquote = "expandable_blockquote"
	EntityCode                 = "code"
	EntityPre                  = "pre"
	EntityTextLink             = "text_link"
	EntityTextMention          = "text_mention"
	EntityCustomEmoji          = "custom_emoji"
	EntityDateTime             = "date_time"
)

// ButtonStyle values for InlineKeyboardButton.Style / KeyboardButton.Style,
// scraped from InlineKeyboardButton.style's docs description (KeyboardButton's
// field carries the identical wording). If omitted, Telegram clients use an
// app-specific default style.
const (
	ButtonStyleDanger  = "danger"
	ButtonStyleSuccess = "success"
	ButtonStylePrimary = "primary"
)

// Parse mode for message text/caption formatting, e.g. SendMessageOptions.ParseMode. Not enumerated anywhere scrapable in the Bot API docs (sendMessage's parse_mode param just links out to "formatting options"), so hand-curated here instead of scraped from scripts/api.json.
const (
	ParseModeHTML       = "HTML"
	ParseModeMarkdownV2 = "MarkdownV2"
	ParseModeMarkdown   = "Markdown"
)

// Emoji accepted by SendDiceRequest.Emoji, selecting the dice animation. The docs prose lists the emoji themselves but never names them, so the Go names here are hand-curated.
const (
	DiceEmojiDice        = "🎲"
	DiceEmojiDarts       = "🎯"
	DiceEmojiBasketball  = "🏀"
	DiceEmojiFootball    = "⚽"
	DiceEmojiBowling     = "🎳"
	DiceEmojiSlotMachine = "🎰"
)

// Chat action accepted by SendChatActionRequest.Action and KeepChatAction. sendChatAction's docs prose lists these inline ("typing for text messages, upload_photo for photos, ...") without a scrapable delimiter, so hand-curated here.
const (
	ChatActionTyping          = "typing"
	ChatActionUploadPhoto     = "upload_photo"
	ChatActionRecordVideo     = "record_video"
	ChatActionUploadVideo     = "upload_video"
	ChatActionRecordVoice     = "record_voice"
	ChatActionUploadVoice     = "upload_voice"
	ChatActionUploadDocument  = "upload_document"
	ChatActionChooseSticker   = "choose_sticker"
	ChatActionFindLocation    = "find_location"
	ChatActionRecordVideoNote = "record_video_note"
	ChatActionUploadVideoNote = "upload_video_note"
)
